// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from '@prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  datasource: {
    // Properti ini yang dicari oleh terminal
    url: process.env.DATABASE_URL,       // pgbouncer port 6543 — untuk query
    // direct port 5432 — untuk migrate
  },
  migrations: {
    seed: 'ts-node prisma/seed.ts',
  },
});
